name: Bug Report
description: Report a bug or an issue in the game.
labels: ["type: minor bug", "status: pending triage"]
title: "Bug Report: "
body:
  - type: markdown
    attributes:
      value: "# PLEASE READ THE [CONTRIBUTING GUIDE](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md) BEFORE OPENING ISSUES!"
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        - label: I have read the [Contributing Guide](https://github.com/FunkinCrew/Funkin/blob/main/docs/CONTRIBUTING.md)
        - label: I have checked the Issues/Discussions pages to see if my issue has already been reported
        - label: I have properly titled my issue

  - type: input
    attributes:
      label: Linux Distribution & Version
      description: Which Linux distribution and version of it are you using?
      placeholder: ex. Pop!_OS, Ubuntu/Debian, Arch (btw)...
    validations:
      required: true

  - type: input
    attributes:
      label: Game Version
      description: Which version are you playing on? The game version is in the bottom left corner of the main menu.
      placeholder: ex. 0.6.3
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Describe your bug."

  - type: markdown
    attributes:
      value: |
        ### Please do not report issues from other engines. These must be reported in their repositories.
        ### Also do notice that issues that are in the base game are likely to not be fixed! Only report issues specific to these builds

  - type: textarea
    attributes:
      label: Description (include any images, videos, errors, or crash logs)
      description: Provide as much detail as you can. The better others understand your issue, the more they can help you!
      placeholder: Describe your issue here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What steps can other people take to reliably encounter this issue?
      placeholder: 1. Open the game...
